/** js sequence diagrams
 *  http://bramp.github.io/js-sequence-diagrams/
 *  (c) 2012-2013 Andrew Brampton (bramp.net)
 *  Simplified BSD license.
 * 
 *  EBNF version of the grammar for diagraming purposes only
 */
document ::= statement*

statement ::=
	( 'title' ':' message (attributes)?
	| 'participant' actor (attributes)?
	| 'note' ('left of' | 'right of' | 'over') actor ':' message (attributes)?
	| actor ( '-' | '--' ) ( '>' | '>>' )? actor ':' message (attributes)?
	)

actor ::= name (as alias)?

attributes ::=  '[' attribute (',' attribute)* ']'

attribute ::= key '=' '"' value '"'

/*
message ::= [^\n]+

actor ::= [^\[\->:\n,]+
*/