/** js sequence diagrams
 *  http://bramp.github.io/js-sequence-diagrams/
 *  (c) 2012-2013 Andrew Brampton (bramp.net)
 *  Simplified BSD license.
 * 
 *  EBNF version of the grammar for diagraming purposes only
 */
document ::= statement*

statement ::=
	( 'title' ':' message
	| 'participant' actor 
	| 'note' ('left of' | 'right of' | 'over') actor ':' message
	| actor ( '-' | '--' ) ( '>' | '>>' )? actor ':' message
	)

/*
message ::= [^\n]+

actor ::= [^\->:\n,]+
*/